name: Create Branch, Pull Request and Merge Pull request

on:
  # Trigger the workflow on push or manually, adjust as necessary
  push:
    branches:
      - main

permissions: write-all

jobs:
  commit-changes-create-pr-and-merge-pr:
    runs-on: ubuntu-latest

    outputs:
      branch-name: $ {{ steps.branch.outputs.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # - name: Generate pull request branch suffix
      #   id: suffix
      #   run: |
      #         suffix=$(date +'%Y%m%d%H%M%S')
      #         echo "::set-output name=value::$(echo $suffix)"

      - name: Create branch
          id: branch
        run: |
              set -xe
              echo "name=$(echo ${{ github.run_id }}-${{ github.run_attempt }})" >> "$GITHUB_OUTPUT"

      - name: Checkout branch
        run: |
              set -xe
              git checkout -b post-${{ steps.branch.outputs.name }}

      - name: Run command - echo to file
        run: echo "testing - date - '$(date +'%Y%m%d%H%M%S')'" >> index.html

      - name: Commit and push new file
        run: |
              set -xe
              git config user.name "chainomi"
              git config user.email "chainomi@gmail.com"
              git add .
              git commit -m "New post"
              git push origin post-${{ steps.suffix.outputs.value }}

      - name: Create pull request
        run: |
              set -xe
              echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
              gh pr create --title "New auto pull request for - branch post-${{ steps.branch.outputs.name }}" --body "This is a PR to add changes to index.html"

      - name: Merge pull request
        run: |
              set -xe
              gh pr merge --auto --delete-branch --squash "post-${{ steps.branch.outputs.name }}"         
