name: Create Branch, Pull Request and Merge Pull request

on:
  # Trigger the workflow on push or manually, adjust as necessary
  push:
    branches:
      - main

jobs:
  commit changes, make PR and merge PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Generate pull request branch suffix
        id: suffix
        run: |
              suffix=$(date +'%Y%m%d%H%M%S')
              echo "::set-output name=value::$(echo $suffix)"

      - name: Example how to use the output
        run: echo "${{ steps.suffix.outputs.value }}"

      - name: create branch
        run: git checkout -b post-${{ steps.suffix.outputs.value }}

      - name: run command - echo to file
        run: echo "testing" >> index.html

      - name: commit and push new file
        run: |
              set -xe
              git config user.name "chainomi"
              git config user.email "chainomi@gmail.com"
              git add .
              git commit -m "New post"
              git push origin post-${{ steps.suffix.outputs.value }}

      - name: create pull request
        run: |
              set -xe
              echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
              gh pr create --title "New auto pull request for - branch post-${{ steps.suffix.outputs.value }}" --body "This is a PR to add changes to index.html"

      - name: merge pull request
        run: |
              set -xe
              gh pr merge --auto --delete-branch --squash "post-${{ steps.suffix.outputs.value }}"         
